Resources:
  FrontendCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: "MyS3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
          CachedMethods: 
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
        Origins:
          - Id: "MyS3Origin"
            DomainName: !Sub "${FrontendBucket}.s3.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${FrontendBucketOAI}"
        Enabled: true
