version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend        # Navigate into the frontend folder once
      - npm install        # Install dependencies in the frontend folder

  build:
    commands:
      - echo Building the frontend...
      - npm run build      # Build the project in the frontend folder (no need to cd again)

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - frontend/dist/**/*  # Include all files from the dist folder inside frontend
    - frontend/frontends-stack.yaml  # Include the CloudFormation stack file
