version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd frontend  # Navigate to the 'frontend' directory where package.json is located
      - npm install  # Install dependencies from package.json
  build:
    commands:
      - echo Build started on `date`
      - npm run build  # If you have a build script defined in package.json
artifacts:
  files:
    - '**/*'  # This includes all files from the frontend directory after the build
