version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install   # Install dependencies in the frontend folder
  build:
    commands:
      - echo Building the frontend...
      - cd frontend
      - npm run build  # Build the project in the frontend folder
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - frontend/dist/**/*  # Include all files in dist folder inside frontend
    - frontend/frontends-stack.yaml  # Include the CloudFormation stack
