version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build   # Make sure this is the correct build command for your project
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - frontend/**/* 
  base-directory: 'dist'   # or the directory where your build output is located
