version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend  # Move into the frontend directory
      - npm install  # Install dependencies
  build:
    commands:
      - echo Building the application...
      - npm run build  # Run the Webpack build process
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - frontend/dist/**  # Include all files from the dist/ directory within frontend
    - frontends-stack.yaml  # Include CloudFormation template from the root
  discard-paths: no
  base-directory: frontend/dist  # Specify the base directory for artifacts
